version: '3'
volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      ports:
        - 5430:5432
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      volumes:
        - ./imports:/opt/jboss/keycloak/imports
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export-brainyoodev.json
        JAVA_OPTS_APPEND: -Dkeycloak.profile=preview -Dkeycloak.profile.feature.token_exchange=enabled -Dkeycloak.profile.feature.upload_scripts=enabled
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev", "--http-relative-path /auth", "--import-realm"]
      ports:
        - 8083:8080
      depends_on:
        - postgres
